[terminal.shell]
args = ['--login']
program = "/usr/bin/zsh"
#args = ["--login", "-c", "tmux new-session -A -s default"]

[window]
opacity = 0.85
resize_increments = true
padding = {x=5, y=5}


[cursor]
style = "Beam"


[colors.normal]
black = "#21222c"
red = "#ff5555"
green = "#50fa7b"
yellow = "#f1fa8c"
blue = "#bd93f9"
magenta = "#ff79c6"
cyan = "#8be9fd"
white = "#f8f8f2"


[colors.primary]
background = "#0C0f16"
foreground = "#f8f8f2"


[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"


[font]
size = 10.0
normal = { family = "Hack Nerd Font Mono", style = "Regular" }


[selection]
save_to_clipboard = true


[keyboard]
bindings = [
  { key = "T", mods = "Control|Shift", chars = "\x01c" },
  { key = ")", mods = "Control|Shift", chars = "\x01%" },
  { key = "=", mods = "Control|Shift", chars = "\x01\"" }
]
