# activar el mouse
set -g mouse on

# Re-enumerar ventanas al cerrar una
set -g renumber-windows on

# Numeración de ventanas desde 1
set -g base-index 1

# Cambiar prefijo a Ctrl+a (opcional, más cómodo)
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Inicializar TPM (debe estar al final del archivo)
set -g @plugin 'tmux-plugins/tpm'

# Tema Dracula
set -g @plugin 'dracula/tmux'

# Configuración opcional de Dracula
set -g @dracula-show-powerline true
set -g @dracula-refresh-rate 10
set -g @dracula-show-battery false

set -g @dracula-right-pad false

set -g status-position bottom
set -g @dracula-show-empty-plugins false

# Inicializar TPM (SIEMPRE al final)
run -b '~/.tmux/plugins/tpm/tpm'
