#! /bin/sh

wmname LG3D &
vmware-user-suid-wrapper &

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 2
bspc config window_gap 6

# bspc config split_ratio 0.42
bspc config split_ratio 0.5
bspc config top_padding 0


bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config pointer_follows_focus true
bspc config focus_follows_pointer true
bspc config click_to_focus true
bspc config click_to_focus_button 1

# Reglas de ventana
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a gnome-calculator: state=pseudo_tiled width=300 height=350
bspc rule -a Qalculate-gtk: state=tiled
bspc rule -a Spotify desktop='^10' state=tiled follow=on
bspc rule -a Pavucontrol: state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# RESOLUCION ARANDR

# WALLPAPER
feh --bg-fill ~/Wallpaper/Imagen_93.jpg

# POLYBAR
~/.config/polybar/launch.sh

# CUSTOM
bspc config focus_follows_pointer false

# PICOM
picom --config ~/.config/picom/picom.conf &

xsetroot -cursor_name left_ptr &

# Colores de bordes
bspc config border_width 3
bspc config focused_border_color "#F16E44" # color de la ventana activa
bspc config normal_border_color "#0D1017"  # color de la ventana inactiva
bspc config presel_feedback_color "#C39BD3"

bspc config auto_fullscreen true

#~/.config/bspwm/scripts/hide_polybar_fullscreen.sh  &
